name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest # https://pnpm.io/installation#compatibility

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Use cached node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
